version: "3.8"
services:
    mymatomo:
        image: matomo
        ports:
            - 80:80
        networks:
            - mynetwork
    mydatabase:
        image: mariadb
        networks:
            - mynetwork
        environment:
            MARIADB_ROOT_PASSWORD: my-secret-root-pw
            MARIADB_DATABASE: matomo_db
            MARIADB_USER: matomo_user
            MARIADB_PASSWORD: my-secret-matomo-pw
networks:
    mynetwork: