version: "3.8"
services:
    mymatomo:
        image: matomo
        ports:
            - 80:80
        environment: 
            MATOMO_DATABASE_HOST: mydatabase
            MATOMO_DATABASE_ADAPTER: mysql
            MATOMO_DATABASE_USERNAME: matomo_user
            MATOMO_DATABASE_PASSWORD: my-secret-matomo-pw
            MATOMO_DATABASE_DBNAME: matomo_db
        networks:
            - mynetwork
    mydatabase:
        image: mariadb
        networks:
            - mynetwork
        environment:
            MARIADB_ROOT_PASSWORD: my-secret-root-pw
            MARIADB_DATABASE: matomo_db
            MARIADB_USER: matomo_user
            MARIADB_PASSWORD: my-secret-matomo-pw
networks:
    mynetwork: